### ISSUE TITLE
Line and block comments wrong format?

### ISSUE THREAD

**Issue by shelbyKiraM** [theusaf/Atom-AutoHotKey#1]
When I press `Ctrl-/` in an AutoHotKey file, it puts:

```
/* start of the line my cursor is in or selection started in to the end of the final line in the selection or cursor was in */
```
I was looking in other codebases for how to do it, maybe Python has a good example?

**Comment by shelbyKiraM** [comment]
I found some in the [Flight Manual on comments](https://flight-manual.atom.io/hacking-atom/sections/creating-a-grammar/#comments)

Here's how it's in the [Python language](https://github.com/atom/language-python/blob/master/grammars/tree-sitter-python.cson#L62)

If you need blocks, too, here's how [C++](https://github.com/atom/language-c/blob/master/grammars/tree-sitter-cpp.cson) handles it. Looks like it might need a conversion to tree-sitter? Idk 🤷🏼‍♀️

**Comment by asbestosbill** [comment]
Maybe I'm misreading what this issue is regarding, but /* and */ _are_ proper comment flags for AutoHotkey, in addition to the semicolon for single-line comments.
